### ISSUE TITLE
1st option is not working properly 

### ISSUE THREAD

**Issue by Yfgig** [xploitstech/Xteam#11]
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11                         Traceback (most recent call last):                                      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range                                   Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):                                      File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 64, in get                                  with contextlib.closing(urlopen(
                            ^^^^^^^^                                    File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 216, in urlopen                                                 return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Xteam/Ig_information_gathering/Core_files/Ig_information_gathering.py", line 20, in <module>
    'user-agent' : UserAgent().random
                   ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/fake.py", line 75, in load
    self.data = load_cached(
                ^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 187, in load
    ret = json.loads(get(
                     ^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by Mu7ul** [comment]
Yeah bro same happening here
